language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  
services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.6-precise
    packages:
      - mongodb-org-server

before_script:
  - sleep 15
  
script: 
  - npm run coverage

after_success: 
  - npm run coveralls
  - npm run generate-site